---
- name: install devel packages
  with_items: "{{ devel_packages }}"
  pkgng:
    name: "{{ item.name }}"
  notify:
    - restart secadm

- name: configure secadm rules
  template:
    src: secadm.rules.j2
    dest: /usr/local/etc/secadm.rules
  notify:
    - restart secadm

- name: enable secadm
  template:
    src: secadm
    dest: /etc/rc.conf.d/secadm
  notify:
    - restart secadm
